ALTER TABLE "SiteSettings"
ADD COLUMN "deliveryPrice" INTEGER NOT NULL DEFAULT 15000,
ADD COLUMN "freeDeliveryEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "freeDeliveryThreshold" INTEGER NOT NULL DEFAULT 350000;
